In [1]:
import pandas as pd

# 1. CSV file ka path (original file)
file_path = 'F:\\InternShip\\Booking.com-Data-Scraping\\pakistan_home_all_cities.csv'  # Apna file ka exact path likho

# 2. CSV load karo
df = pd.read_csv(file_path)

# 3. "Scored " text remove karke numeric me convert karo
df['Rating'] = df['Rating'].str.replace('Scored ', '', regex=False).astype(float)

# 4. Price column ko remove karo (agar exist karta hai)
if 'Price' in df.columns:
    df.drop(columns=['Price'], inplace=True)

# 5. Same file overwrite karke save karo
df.to_csv(file_path, index=False)

print(f"File '{file_path}' updated successfully! 'Rating' cleaned & 'Price' column removed.")

AttributeError: Can only use .str accessor with string values!

In [14]:
df.head()

,City,Property Type,Name,Rating,Reviews Count,Location,Image URL,Image Path
0,Karachi,home,Charming Home banglow,9.4,9.0,"Clifton, Karachi",https://cf.bstatic.com/xdata/images/hotel/squa...,images_home\Charming_Home_banglow.jpg
1,Karachi,home,Charming luxury home,10.0,10.0,"Clifton, Karachi",https://cf.bstatic.com/xdata/images/hotel/squa...,images_home\Charming_luxury_home.jpg
2,Karachi,home,Luxury Living Penthouse Gulshan Iqbal Block#7,9.1,9.0,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_home\Luxury_Living_Penthouse_Gulshan_Iq...
3,Karachi,home,Dream home 2 & 4 bedroom Family house,8.0,8.0,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_home\Dream_home_2___4_bedroom_Family_ho...
4,Karachi,home,Home Sweet Home 3 bed Banglow,10.0,10.0,"D.H.A., Karachi (D.H.A.)",https://cf.bstatic.com/xdata/images/hotel/squa...,images_home\Home_Sweet_Home_3_bed_Banglow.jpg

In [15]:
import pandas as pd

# 1. CSV file ka path (original file)
file_path = 'F:\\InternShip\\Booking.com-Data-Scraping\\pakistan_apartment_all_cities.csv'  # Apna file ka exact path likho

# 2. CSV load karo
df = pd.read_csv(file_path)

# 3. "Scored " text remove karke numeric me convert karo
df['Rating'] = df['Rating'].str.replace('Scored ', '', regex=False).astype(float)

# 4. Price column ko remove karo (agar exist karta hai)
if 'Price' in df.columns:
    df.drop(columns=['Price'], inplace=True)

# 5. Same file overwrite karke save karo
df.to_csv(file_path, index=False)

print(f"File '{file_path}' updated successfully! 'Rating' cleaned & 'Price' column removed.")

File 'F:\InternShip\Booking.com-Data-Scraping\pakistan_apartment_all_cities.csv' updated successfully! 'Rating' cleaned & 'Price' column removed.

In [16]:
df.head()

,City,Property Type,Name,Rating,Reviews Count,Location,Image URL,Image Path
0,Karachi,apartment,Room for rent,NaN,NaN,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_apartment\Room_for_rent.jpg
1,Karachi,apartment,Prestige comfort apartments separate lounge wi...,NaN,NaN,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_apartment\Prestige_comfort_apartments_s...
2,Karachi,apartment,YS Rooms,NaN,NaN,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_apartment\YS_Rooms.jpg
3,Karachi,apartment,Prestige Comfort,NaN,NaN,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_apartment\Prestige_Comfort.jpg
4,Karachi,apartment,Prestige comforts,NaN,NaN,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_apartment\Prestige_comforts.jpg

In [17]:
import pandas as pd

# 1. CSV file ka path (original file)
file_path = 'F:\\InternShip\\Booking.com-Data-Scraping\\pakistan_hotel_all_cities.csv'  # Apna file ka exact path likho

# 2. CSV load karo
df = pd.read_csv(file_path)

# 3. "Scored " text remove karke numeric me convert karo
df['Rating'] = df['Rating'].str.replace('Scored ', '', regex=False).astype(float)

# 4. Price column ko remove karo (agar exist karta hai)
if 'Price' in df.columns:
    df.drop(columns=['Price'], inplace=True)

# 5. Same file overwrite karke save karo
df.to_csv(file_path, index=False)

print(f"File '{file_path}' updated successfully! 'Rating' cleaned & 'Price' column removed.")

File 'F:\InternShip\Booking.com-Data-Scraping\pakistan_hotel_all_cities.csv' updated successfully! 'Rating' cleaned & 'Price' column removed.

In [18]:
df.head()

,City,Property Type,Name,Rating,Reviews Count,Location,Image URL,Image Path
0,Karachi,hotel,Imperial Inn Hotel,NaN,NaN,"PECHS, Karachi",https://cf.bstatic.com/xdata/images/hotel/squa...,images_hotel\Imperial_Inn_Hotel.jpg
1,Karachi,hotel,Karachi Marriott Hotel,8.4,8.0,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_hotel\Karachi_Marriott_Hotel.jpg
2,Karachi,hotel,"Pearl Continental Hotel, Karachi",7.2,7.0,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_hotel\Pearl_Continental_Hotel__Karachi.jpg
3,Karachi,hotel,Mövenpick Hotel Karachi,7.3,7.0,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_hotel\M_venpick_Hotel_Karachi.jpg
4,Karachi,hotel,LOKAL Flagship x Karachi - DHA,8.6,8.0,Karachi,https://cf.bstatic.com/xdata/images/hotel/squa...,images_hotel\LOKAL_Flagship_x_Karachi_-_DHA.jpg

In [19]:
import pandas as pd

# 1. Apni 3 CSV file paths likho
file1 = 'F:\\InternShip\\Booking.com-Data-Scraping\\pakistan_apartment_all_cities.csv'
file2 = 'F:\\InternShip\\Booking.com-Data-Scraping\\pakistan_home_all_cities.csv'
file3 = 'F:\\InternShip\\Booking.com-Data-Scraping\\pakistan_hotel_all_cities.csv'

# 2. CSV files ko read karo
df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)
df3 = pd.read_csv(file3)

# 3. Combine (vertically append) karo
combined_df = pd.concat([df1, df2, df3], ignore_index=True)

# 4. Nayi file ka naam set karo
output_file = 'property_booking.csv'

# 5. Save karo
combined_df.to_csv(output_file, index=False)

print(f"Combined CSV saved as {output_file}")

Combined CSV saved as property_booking.csv